steps:
  - label: 'Check Documentation'
    commands:
      - gem install bundler
      - bundle install
      - bundle exec standardrb
      - .buildkite/scripts/tests/check_for_documentation.rb

  - label: 'Taylor Build'
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake linux:release:build
      - cd dist/linux/release
      - buildkite-agent artifact upload taylor

  - wait

  - label: "Build base export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:base

  - wait

  - label: "Build Android export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:android

  - wait

  - label: "Build Linux export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:linux

  - wait

  - label: "Build OSX export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:osx

  - wait

  - label: "Build Windows export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:windows

  - wait

  - label: "Build Web export image"
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake docker:build:export:web

  - wait

  - label: 'CLI Tool Tests'
    commands:
      - buildkite-agent artifact download taylor /usr/bin/
      - chmod +x /usr/bin/taylor
      - cd ./cli-tool/
      - taylor ./cli.rb test/test.rb
      - ../.buildkite/scripts/tests/upload_test_analytics.sh ./test-analytics.json

  - label: 'Taylor Tests - Export'
    commands:
      - buildkite-agent artifact download taylor /usr/bin/
      - chmod +x /usr/bin/taylor
      - .buildkite/scripts/tests/export.sh

  - wait

  - label: 'Taylor Tests - Linux'
    commands:
      - .buildkite/scripts/tests/test_suite_linux.sh
      - .buildkite/scripts/tests/upload_test_analytics.sh /tmp/buildkite/taylor-test-suite/linux/test-analytics.json

  - label: 'Taylor Tests - Windows'
    commands:
      - .buildkite/scripts/tests/test_suite_windows.sh
      - .buildkite/scripts/tests/upload_test_analytics.sh /tmp/buildkite/taylor-test-suite/windows/test-analytics.json

  - label: 'Taylor Tests - Web'
    commands:
      - .buildkite/scripts/tests/test_suite_web.sh
