---
name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build"
        run: |
          rake docker:build
          ./scripts/generate_release_body.rb > release-body.md

      - uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          bodyFile: release-body.md
          artifacts: |
            ./releases/*.zip
