---
name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      -
        uses: actions/checkout@v2

      -
        name: "Get git tag"
        id: tag
        uses: dawidd6/action-get-tag@v1

      -
        name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: "Setup Dockerfile"
        env:
          VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          envsubst < ./scripts/export/Dockerfile.template > ./scripts/export/Dockerfile

      -
        name: "Build Docker"
        uses: docker/build-push-action@v2
        with:
          context: ./scripts/export/
          push: false
          tags: ${{secrets.DOCKER_USERNAME}}/taylor:latest,${{secrets.DOCKER_USERNAME}}/taylor:${{steps.tag.outputs.tag}}

      -
        name: "Compile Taylor CLI"
        env:
          VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          cd ./cli-tool
          docker run -u $(id -u ${USER}):$(id -g ${USER}) --mount type=bind,source=$(pwd),target=/app/game/ hellrok/taylor:$VERSION
          mkdir ../exports
          mv ./exports/* ../exports/

      -
        name: "Push Docker"
        uses: docker/build-push-action@v2
        with:
          context: ./scripts/export/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/taylor:latest,${{secrets.DOCKER_USERNAME}}/taylor:${{steps.tag.outputs.tag}}

      - name: "Write release body"
        run: |
          ./scripts/generate_release_body.rb > release-body.md

      - uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          bodyFile: release-body.md
          artifacts: |
            ./exports/*.zip
